[project]
name = "back"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.121.1",
    "sqlmodel>=0.0.27",
    "psycopg2-binary>=2.9.9",
]
